"""Initial Migration

Revision ID: d801aadf7b2e
Revises: c706a891882f
Create Date: 2019-03-04 16:54:27.216623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd801aadf7b2e'
down_revision = 'c706a891882f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_username', table_name='comments')
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_comments_username', 'comments', ['username'], unique=False)
    # ### end Alembic commands ###
